services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: oms-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "Strong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oms-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  sql_data:
